pessoa/urls.py
from django.urls import path

from pessoa.views import (Follow, Home, ProfileEditor, Registration,
                          UserDetail, UserList)

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('cadastro/', Registration.as_view(), name='registration'),
    path('editor-perfil/', ProfileEditor.as_view(), name='profile-editor'),
    path('usuarios/', UserList.as_view(), name='usuarios'),
    path('seguir/<int:user_id>', Follow.as_view(), name='follow'),
    path('<str:username>/', UserDetail.as_view(), name='perfil'),
]

piado/urls.py
from django.urls import path
from piado.views import (HashtagList, HashtagPiadosList, PiadoCreate, PiadoDelete,
                         PiadoLike, RePiado, PiadoView, PiadoComment)

urlpatterns = [
    path('adicionar/', PiadoCreate.as_view(), name='piado-create'),
    path('remover/<int:pk>/', PiadoDelete.as_view(), name='piado-delete'),
    path('curtir/<int:pk>/', PiadoLike.as_view(), name='piado-like'),
    path('repiar/<int:pk>/', RePiado.as_view(), name='repiar'),
    path('<int:pk>/', PiadoView.as_view(), name='piado-detail'),
    path('comentario/<int:hospedeiro>/', PiadoComment.as_view(), name='piado-comment'),
    path('hashtags/', HashtagList.as_view(), name='hashtag'),
    path('hashtags/<slug:hashtag>/', HashtagPiadosList.as_view(), name='hashtag-piado'),
]

piadouro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from piadouro.settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('django.contrib.auth.urls')),
    path('piado/', include('piado.urls')),
    path('', include('pessoa.urls'))
] + static(STATIC_URL, document_root=STATIC_ROOT) + static(MEDIA_URL, document_root=MEDIA_ROOT)

pessoa/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

ESTADO_CIVIL = (
    ('s', 'Solteiro'),
    ('n', 'Namorando'),
    ('no', 'Noivado'),
    ('c', 'Casado'),
    ('v', 'Viuvo'),
    ('p', 'Piranhage'),
)

ESTADOS = (
    ('rs', 'Rio Grande do Sul'),
    ('sc', 'Santa catarina'),
    ('pr', 'Paraná'),
)

def validador_idade(data_nascimento):
    hoje = date.today()
    delta = hoje - data_nascimento

    if delta.days / 365.25 < 18:
        raise ValidationError(
            'Sai fora menó',
            params={'value': data_nascimento},
        )


class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name='perfil')
    foto = models.ImageField(upload_to='piadouro/imagens/')
    telefone = models.CharField(max_length=20)
    estado_civil = models.CharField(max_length=2, choices=ESTADO_CIVIL)
    data_nascimento = models.DateField(validators=[validador_idade])
    estado = models.CharField(max_length=2, choices=ESTADOS)
    cidade = models.CharField(max_length=64)
    desempregado = models.BooleanField()

    seguindo = models.ManyToManyField(User, related_name='seguidores', symmetrical=False, blank=True)

    def __str__(self):
        return f'{self.usuario}'

pessoa/forms.py
from django.forms import ModelForm, inlineformset_factory, CharField, PasswordInput, Select
from django.contrib.auth.models import User
from pessoa.models import Perfil

class UserForm(ModelForm):
    password2 = CharField(max_length=60, required=True, widget=PasswordInput())

    class Meta:
        model = User
        exclude = [
            'is_staff',
            'is_active',
            'date_joined',
            'last_login',
            'groups',
            'user_permissions',
            'is_superuser',
        ]
        widgets = {
            'password': PasswordInput()
        }


class UserEditorForm(ModelForm):
    class Meta:
        model = User
        exclude = [
            'is_staff',
            'is_active',
            'date_joined',
            'last_login',
            'groups',
            'user_permissions',
            'is_superuser',
            'password',
        ]

class UserProfileForm(ModelForm):
    class Meta:
        model = Perfil
        exclude = ['usuario', 'seguindo']

pessoa/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.base import RedirectView, TemplateView
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from pessoa.models import Perfil
from django.contrib.auth.mixins import LoginRequiredMixin
from pessoa.forms import UserProfileForm, UserForm, UserEditorForm
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse
from piado.models import Piado
from django.db.models import Q
from piadouro.mixins.page_title import PageTitleMixin


class Home(PageTitleMixin, LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

    def get_page_title(self):
        return f'Home de {self.request.user.first_name}'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        q = self.request.GET.get('q', False)
        if not q:
            context['piados'] = Piado.objects.filter(
                Q(proprietario=self.request.user) |
                Q(proprietario__in=self.request.user.perfil.seguindo.all())
            )
        else:
            context['piados'] = Piado.objects.filter(conteudo__icontains=q)
            context['q'] = q
        return context

class UserDetail(PageTitleMixin, LoginRequiredMixin, DetailView):
    model = User
    template_name = 'home.html'

    def get_page_title(self):
        return f'Timeline de {self.object.first_name}'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(self.model, username=self.kwargs['username'])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['piados'] = Piado.objects.filter(proprietario=self.object)
        return context

class UserList(PageTitleMixin, LoginRequiredMixin, ListView):
    template_name = 'user_list.html'
    model = Perfil
    page_title = 'Lista de usuários'


class Follow(LoginRequiredMixin, RedirectView):
    permanent = False
    query_string = False
    pattern_name = 'usuarios'

    def get_redirect_url(self, *args, **kwargs):
        user_to_follow = get_object_or_404(User, pk=kwargs['user_id'])
        if self.request.user.perfil.seguindo.filter(pk=user_to_follow.pk).exists():
            self.request.user.perfil.seguindo.remove(user_to_follow)
        else:
            self.request.user.perfil.seguindo.add(user_to_follow)
        return super().get_redirect_url()


class Registration(PageTitleMixin, CreateView):
    model = User
    template_name = 'create_user.html'
    form_class = UserForm
    page_title = 'Crie sua conta'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'action': reverse('registration'),
            'button_text': 'Cadastrar'
        })
        context['form'] = self.get_form()
        if self.request.method == 'POST':
            context['profile_form'] = UserProfileForm(self.request.POST, self.request.FILES)
        else:
            context['profile_form'] = UserProfileForm()
        return context


    def post(self, request, *args, **kwargs):
        self.object = None
        context = self.get_context_data()

        if context['form'].is_valid() and context['profile_form'].is_valid():
            user = context['form'].save(commit=False)
            user.set_password(context['form'].cleaned_data['password'])
            user.save()
            context['profile_form'].instance.usuario = user
            context['profile_form'].save()
            new_user = authenticate(
                request,
                username=context['form'].cleaned_data['username'],
                password=context['form'].cleaned_data['password'],
            )
            login(request, new_user)
            return redirect('home')
        return self.render_to_response(context)

class ProfileEditor(PageTitleMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'create_user.html'
    form_class = UserEditorForm
    page_title = 'Editar perfil'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.request.user.id)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'action': reverse('profile-editor'),
            'button_text': 'Atualizar'
        })
        self.object = self.get_object()
        context['form'] = self.get_form()
        if self.request.method == 'POST':
            context['profile_form'] = UserProfileForm(self.request.POST, self.request.FILES, instance=self.object.perfil)
        else:
            context['profile_form'] = UserProfileForm(instance=self.object.perfil)
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        context = self.get_context_data()

        if context['form'].is_valid() and context['profile_form'].is_valid():
            user = context['form'].save()
            context['profile_form'].save()
            return redirect('home')
        return self.render_to_response(context)

pessoa/templates/create_user.html
{% extends 'base.html' %}

{% block seguidores %}{% endblock seguidores %}

{% block principal %}
  <div class="col s12 m6 offset-m3">
    <div class="card">
      <form id="registration-form" action="{{ action }}" method="POST" class="card-content row" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_fields_errors }}
        {{ profile_form.non_fields_errors }}
        <div class="input-field col s12 m6">
          {{ form.first_name }}
          <label for="id_first_name">{{ form.first_name.label }}</label>
          {{ form.first_name.errors }}
        </div>
        <div class="input-field col s12 m6">
          {{ form.last_name }}
          <label for="id_last_name">{{ form.last_name.label }}</label>
          {{ form.last_name.errors }}
        </div>

        <div class="input-field col s12">
          {{ form.username }}
          <label for="id_username">{{ form.username.label }}</label>
          {{ form.username.help_text }}
          {{ form.username.errors }}
        </div>

        <div class="input-field col s12">
          {{ form.email }}
          <label for="id_email">{{ form.email.label }}</label>
          {{ form.email.errors }}
        </div>

        <div class="input-field col s12 m6">
          {{ form.password }}
          <label for="id_password">{{ form.password.label }}</label>
          {{ form.password.errors }}
        </div>

        <div class="input-field col s12 m6">
          {{ form.password2 }}
          <label for="id_password2">{{ form.password2.label }}</label>
          {{ form.password2.errors }}
        </div>

        <div class="input-field col s12 m6">
          {{ profile_form.telefone }}
          <label for="id_telefone">{{ profile_form.telefone.label }}</label>
          {{ profile_form.telefone.errors }}
        </div>

        <div class="input-field col s12 m6">
          {{ profile_form.estado_civil }}
          <label for="id_estado_civil">{{ profile_form.estado_civil.label }}</label>
        </div>

        <div class="input-field col s12 m6">
          {{ profile_form.data_nascimento }}
          <label for="id_data_nascimento">{{ profile_form.data_nascimento.label }}</label>
          {{ profile_form.data_nascimento.errors }}
        </div>
        <p class="col s12 m6 checkbox">
          <label>
            {{ profile_form.desempregado }}
            <span>{{ profile_form.desempregado.label }}</span>
          </label>
        </p>

        <div class="input-field col s12 m6">
          {{ profile_form.estado }}
          <label for="id_estado">{{ profile_form.estado.label }}</label>
        </div>
        <div class="input-field col s12 m6">
          {{ profile_form.cidade }}
          <label for="id_cidade">{{ profile_form.cidade.label }}</label>
          {{ profile_form.cidade.errors }}
        </div>

        <div class="file-field input-field col s12">
          <div class="btn">
            <span>Foto</span>
            {{ profile_form.foto }}
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
          {{ profile_form.foto.errors }}
        </div>
      </form>
      <div class="card-action right-align">
        <button form="registration-form" class="waves-effect waves-teal btn-flat" type="submit">{{ button_text }}</button>
      </div>
    </div>
  </div>
{% endblock principal %}

pessoa/templates/home.html
{% extends 'base.html' %}
{% load user_in %}

{% block principal %}
{{form.errors}}
  <div class="col s12 m6 offset-m3 offset-l1">
    {% if request.path == '/' %}
    <div class="row">
      <form class="col s12 piar" method="POST" action="{% url 'piado-create' %}">
        {% csrf_token %}
        <div class="row">
          <div class="input-field col s10">
            <textarea id="piado_principal" class="materialize-textarea" name="conteudo"></textarea>
            <label for="piado_principal">Da um piu ai</label>
          </div>
        </div>
      </form>
    </div>
    {% endif %}
    <div class="row">
      {% for piado in piados %}
        <div class="col s12">
          {% include 'piado/piado.html' %}
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock principal %}

pessoa/templates/user_list.html
{% extends "base.html" %}

{% load user_in %}

{% block seguidores %}{% endblock seguidores %}

{% block principal %}
  <div class="col s12 m8 l6 offset-m2 offset-l3 ">
    <ul class="collection">
      {% for profile in object_list %}
        {% if profile.usuario.id != request.user.id %}
          <li class="collection-item avatar">
            <img src="{{ profile.foto.url }}" alt="" class="circle">
            <a href="{% url 'perfil' profile.usuario.username %}" class="title">{{ profile.usuario.username.title }}</a>
            <p>
              Seguidores: {{ profile.seguidores.count }} | Seguindo: {{ profile.seguindo.count }}
              <br>
              Piados: {{ profile.piados.count }}
            </p>
            <a href="{% url 'follow' profile.usuario.id %}" class="secondary-content">
              <i class="material-icons">
                {% if profile.usuario|exists:request.user.perfil.seguindo.all %}
                  favorite
                {% else %}
                  favorite_border
                {% endif %}
              </i>
            </a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
{% endblock principal %}